# Generated by Django 5.1 on 2024-08-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.URLField(),
        ),
    ]
