# Generated by Django 5.1 on 2024-08-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_artist_options_alter_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='listen',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
