# Generated by Django 5.1 on 2024-08-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_song_listen'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='seen',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='seen',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
